[package]
name = "pos-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4.8", features = ["postgres", "uuidv07", "r2d2"] }
dotenv = "0.15.0"
uuid = { version = "0.8.2", features = ["v4", "serde"]}
env_logger = "0.9.0"
r2d2 = "0.8.9"