version: '3'

services:
  pos-rs:
    image: pos-rs
    ports:
      - 8000:80
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/pos_rs
      - REDIS_URL=redis://redis:6379
      - SECRET=${SECRET}

  db:
    image: postgres
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos_rs

  redis:
    image: redis
    volumes:
      - redis:/data
    command: redis-server --save 60 1 --loglevel warning


volumes:
  redis:
  psql: